# BERTopic Modeling

### Loading necessary libraries

In [ ]:
import pandas as pd
from bertopic import BERTopic
from sentence_transformers import SentenceTransformer
from bertopic.representation import MaximalMarginalRelevance

## EDA & Preprocessing

### Loading and Previewing Dataset

In [5]:
# Define the path to the CSV file
file_path = "../data/spotify_reviews_clean&PP_NoEmoji_V2.csv"

# Load the dataset from the specified CSV file using pandas
data = pd.read_csv(file_path)

# Display the first five rows of the dataframe to check the data's initial structure
data.head()

,reviewId,userName,content,score,thumbsUpCount,reviewCreatedVersion,at,appVersion,thumbsUpBins,review_length,review_word_count,language,emojis
0,deaff34b-8743-47ee-b464-1d797e3ac0b1,Katie Watson,spotify extremely degraded time let non premiu...,1,3349,8.9.34.590,2024-04-30 14:12:05,8.9.34.590,1001-10000,473,86,en,[]
1,94918b0a-9544-4d68-a903-4b65777560e0,Gurnam Kaur Bajwa,frustrate playback issue spotify use music app...,1,2585,8.9.32.624,2024-04-21 16:20:35,8.9.32.624,1001-10000,424,73,en,[]
2,e709d597-ae44-49c1-aef3-f9655b25ee69,Bhavithra Srinivasan,spotify year song need become worse day day wi...,2,268,8.9.34.590,2024-04-28 17:22:27,8.9.34.590,101-1000,483,89,en,[]
3,7004d18f-feb7-4a89-a1dd-051cfe907ad9,Anushma Roy,new update absolutely disgust feature availabl...,1,298,8.9.32.624,2024-04-27 17:33:08,8.9.32.624,101-1000,345,62,en,[]
4,dbed7578-afc9-4a58-b426-ce9adef1cf61,Yohan Billimoria,premium user app become utter garbage music pl...,1,1303,8.9.34.590,2024-04-27 05:14:29,8.9.34.590,1001-10000,500,93,en,[]

### Data Preprocessing

In [4]:
# Extracting reviews into a list from the 'content' column
reviews = data['content'].tolist()

## Initializing Topic Modeling

In [5]:
# Creating a topic model with detailed settings

# Load the all-MiniLM-L6-v2 model from sentence-transformers
embedding_model = SentenceTransformer('all-MiniLM-L6-v2')
# Load the MaximalMarginalelevance model to increase granularity
representation_model = MaximalMarginalRelevance(diversity=0.7)

# Initialize BERTopic
topic_model = BERTopic(language="english", calculate_probabilities=True,
                       verbose=True, representation_model=representation_model,
                       top_n_words=10, embedding_model=embedding_model, min_topic_size=10)

modules.json:   0%|          | 0.00/349 [00:00<?, ?B/s]

config_sentence_transformers.json:   0%|          | 0.00/116 [00:00<?, ?B/s]

README.md:   0%|          | 0.00/10.7k [00:00<?, ?B/s]

sentence_bert_config.json:   0%|          | 0.00/53.0 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/612 [00:00<?, ?B/s]

model.safetensors:   0%|          | 0.00/90.9M [00:00<?, ?B/s]

tokenizer_config.json:   0%|          | 0.00/350 [00:00<?, ?B/s]

vocab.txt:   0%|          | 0.00/232k [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/466k [00:00<?, ?B/s]

special_tokens_map.json:   0%|          | 0.00/112 [00:00<?, ?B/s]

1_Pooling/config.json:   0%|          | 0.00/190 [00:00<?, ?B/s]

## Topic Modeling on all Reviews

### Fitting the Topic Model to Reviews

In [6]:
# Generating topics and their probabilities
topics, probabilities = topic_model.fit_transform(reviews)

2024-05-30 10:43:12,529 - BERTopic - Embedding - Transforming documents to embeddings.

Batches:   0%|          | 0/2257 [00:00<?, ?it/s]

2024-05-30 11:06:23,675 - BERTopic - Embedding - Completed ✓
2024-05-30 11:06:23,682 - BERTopic - Dimensionality - Fitting the dimensionality reduction algorithm
2024-05-30 11:08:33,486 - BERTopic - Dimensionality - Completed ✓
2024-05-30 11:08:33,495 - BERTopic - Cluster - Start clustering the reduced embeddings
/usr/local/lib/python3.10/dist-packages/joblib/externals/loky/backend/fork_exec.py:38: RuntimeWarning: os.fork() was called. os.fork() is incompatible with multithreaded code, and JAX is multithreaded, so this will likely lead to a deadlock.
  pid = os.fork()
2024-05-30 11:15:34,026 - BERTopic - Cluster - Completed ✓
2024-05-30 11:15:34,067 - BERTopic - Representation - Extracting topics from clusters using representation models.
2024-05-30 11:16:22,496 - BERTopic - Representation - Completed ✓

In [7]:
# Getting information about the topics found in the dataset
topic_info = topic_model.get_topic_info()

### Saving the Fitted Model

In [8]:
topic_model.save("spotify_reviews_topic_model")

2024-05-30 11:16:25,330 - BERTopic - WARNING: When you use `pickle` to save/load a BERTopic model,please make sure that the environments in which you saveand load the model are **exactly** the same. The version of BERTopic,its dependencies, and python need to remain the same.

### Visualizations of Topics

In [9]:
# Printing number of Topics
freq = topic_model.get_topic_info()
print("Number of topics: {}".format( len(freq)))
freq.head()

Number of topics: 249

,Topic,Count,Name,Representation,Representative_Docs
0,-1,47112,-1_app_spotify_play_premium,"[app, spotify, play, premium, add, also, work,...",[great music app almost every song think lose ...
1,0,5502,0_podcast_rogan_jre_listen,"[podcast, rogan, jre, listen, pause, content, ...","[spotify app also music podcasts like listen, ..."
2,1,1041,1_restart_randomly_spotify_phone,"[restart, randomly, spotify, phone, problem, p...",[love spotify use year since update work right...
3,2,1013,2_playlist_smart_random_add,"[playlist, smart, random, add, button, please,...",[spotify use let shuffle song like one artist ...
4,3,937,3_premium_version_skip_money,"[premium, version, skip, money, limit, youtube...",[use good everything need premium version even...

In [10]:
print(topic_model.get_topic_info())

     Topic  Count                                        Name  \
0       -1  47112                 -1_app_spotify_play_premium
1        0   5502                  0_podcast_rogan_jre_listen
2        1   1041            1_restart_randomly_spotify_phone
3        2   1013                 2_playlist_smart_random_add
4        3    937                3_premium_version_skip_money
..     ...    ...                                         ...
244    243     10          243_duolingo_wiggle_monthy_suicide
245    244     10  244_advertising_enjoyment_biggest_delusion
246    245     10              245_quality_thn_signal_surface
247    246     10              246_history_spatial_zoom_atmos
248    247     10               247_ps5_m40_unresponsive_fold

                                        Representation  \
0    [app, spotify, play, premium, add, also, work,...
1    [podcast, rogan, jre, listen, pause, content, ...
2    [restart, randomly, spotify, phone, problem, p...
3    [playlist, smart, random, add, button, please,...
4    [premium, version, skip, money, limit, youtube...
..                                                 ...
244  [duolingo, wiggle, monthy, suicide, becouse, r...
245  [advertising, enjoyment, biggest, delusion, va...
246  [quality, thn, signal, surface, troublesome, a...
247  [history, spatial, zoom, atmos, dolby, ability...
248  [ps5, m40, unresponsive, fold, interval, aspec...

                                   Representative_Docs
0    [great music app almost every song think lose ...
1    [spotify app also music podcasts like listen, ...
2    [love spotify use year since update work right...
3    [spotify use let shuffle song like one artist ...
4    [use good everything need premium version even...
..                                                 ...
244  [great love app old new music access via phone...
245  [spotify way like nice music application also ...
246  [use spotify year guess app change visual stuf...
247  [add option remove listen history cant even fo...
248  [app amazing every aspect except advertisement...

[249 rows x 5 columns]

In [11]:
# Intertopic Distance Map
topic_model.visualize_topics()

In [12]:
# Barchart visualisation to show top 10 topics to understand which words contribute to out topics
topic_model.visualize_barchart(width = 200, height = 330, top_n_topics = 10, n_words = 10)

In [13]:
# Hierarchical visualization to show the relationship between topics
topic_model.visualize_hierarchy()

In [14]:
# Heatmap visualization to show similarities between topics
topic_model.visualize_heatmap(n_clusters=20)

### Topics Over Time

In [15]:
# Ensure timestamps are datetime objects
data['at'] = pd.to_datetime(data['at'])
timestamps = data['at'].tolist()

# Set the number of bins for temporal analysis
nr_bins = 10  # Adjust this based date range and desired granularity

# Generate the topics over time data using the parameters
topics_over_time = topic_model.topics_over_time(docs=reviews, topics=topics, timestamps=timestamps, nr_bins=nr_bins)

# Visualize the topics over time
topic_model.visualize_topics_over_time(topics_over_time, top_n_topics= 10)

10it [05:19, 31.90s/it]

## Topic Modeling 01/11/2023 - 01/02/2024

### Filtering reviews to specified date range

In [16]:
# Ensure timestamps are datetime objects for the entire dataset
data['at'] = pd.to_datetime(data['at'])

# Filtering reviews from November 2023 to January 2024
nov_jan_reviews = data[(data['at'] >= '2023-11-01') & (data['at'] < '2024-02-01')]

# Displaying the first few rows of the filtered reviews
nov_jan_reviews.head()

,reviewId,userName,content,score,thumbsUpCount,reviewCreatedVersion,at,appVersion,thumbsUpBins,review_length,review_word_count,emojis
2845,c113a900-d130-4c13-8cd1-4ef855e3c2c3,c v,pro spotify allows create playlist follow arti...,3,12,8.8.96.364,2024-01-16 01:42:36,8.8.96.364,11-100,500,91,[]
4354,4369d834-b8a8-4e91-95f0-2610f0b82516,Alisha Anwar,good quality great make playlist find song how...,3,587,8.8.96.364,2024-01-03 11:51:36,8.8.96.364,101-1000,399,72,[]
4357,468d5753-a64b-4285-99b5-c1b8a1a2badb,Jon Nehring,overall lot option select quality good app iss...,4,268,8.8.96.364,2023-12-22 19:17:01,8.8.96.364,101-1000,466,83,[]
4358,e12b14fc-7a21-4004-add3-9cd7b08c77a5,Elianah S.,even enjoy time spotify especially bluetooth h...,2,958,8.9.4.304,2024-01-14 00:13:48,8.9.4.304,101-1000,483,81,[]
4359,42f23747-d626-4a2c-a8a9-80902c3f7995,Carina Becker,love app especially basically listen music who...,3,212,8.9.6.458,2024-01-25 07:45:23,8.9.6.458,101-1000,377,70,[]

### Fitting Topic Model to Filtered Date

In [17]:
# Fitting the topic model to the filtered review content
filtered_topics, filtered_probs = topic_model.fit_transform(nov_jan_reviews['content'])

# Getting topic information for the newly filtered content
filtered_topic_info = topic_model.get_topic_info()

2024-05-30 11:22:30,361 - BERTopic - Embedding - Transforming documents to embeddings.

Batches:   0%|          | 0/412 [00:00<?, ?it/s]

2024-05-30 11:26:02,679 - BERTopic - Embedding - Completed ✓
2024-05-30 11:26:02,682 - BERTopic - Dimensionality - Fitting the dimensionality reduction algorithm
2024-05-30 11:26:18,818 - BERTopic - Dimensionality - Completed ✓
2024-05-30 11:26:18,821 - BERTopic - Cluster - Start clustering the reduced embeddings
2024-05-30 11:26:26,410 - BERTopic - Cluster - Completed ✓
2024-05-30 11:26:26,423 - BERTopic - Representation - Extracting topics from clusters using representation models.
2024-05-30 11:26:41,708 - BERTopic - Representation - Completed ✓

In [18]:
freq = topic_model.get_topic_info()
print("Number of topics: {}".format( len(freq)))
freq.head()

Number of topics: 85

,Topic,Count,Name,Representation,Representative_Docs
0,-1,7217,-1_app_play_spotify_premium,"[app, play, spotify, premium, shuffle, add, ch...",[use able listen whatever want new update caus...
1,0,902,0_podcast_listen_still_video,"[podcast, listen, still, video, app, pay, scro...",[use app podcasts music issue podcast playlist...
2,1,540,1_work_spotify_offline_app,"[work, spotify, offline, app, start, wifi, car...",[love spotify lately even get one song music s...
3,2,461,2_premium_skip_minute_listen,"[premium, skip, minute, listen, version, adver...",[every song play every one minute get minute s...
4,3,242,3_lyric_load_fix_say,"[lyric, load, fix, say, please, app, really, a...",[love app lyric come say load lyric song pleas...

### Visualizing Filtered Topics

In [19]:
# Intertopic Distance Map
topic_model.visualize_topics()

In [25]:
# Barchart visualisation to show top 10 topics to understand which words contribute to out topics
topic_model.visualize_barchart(width=300, height=330, top_n_topics=8, n_words = 10)

In [21]:
# Hierarchical visualization to show the relationship between topics
topic_model.visualize_hierarchy()

In [22]:
# Heatmap visualization to show similarities between topics
topic_model.visualize_heatmap(n_clusters=20)

### Generating Topics Over Time to Identify Relevant Topics

In [23]:
# Extract timestamps for the filtered reviews for temporal analysis
timestamps = nov_jan_reviews['at'].tolist()

# Check the lengths of each component
print("Length of nov_jan_reviews['content']:", len(nov_jan_reviews['content']))
print("Length of filtered_topics:", len(filtered_topics))
print("Length of timestamps:", len(timestamps))

# If lengths are the same, proceed with topic modeling over time
if len(nov_jan_reviews['content']) == len(filtered_topics) == len(timestamps):
    # Set the number of bins for temporal analysis
    nr_bins = 10  # Adjust this based on your filtered data's date range and granularity

    # Generate the topics over time data using the corrected parameters
    topics_over_time = topic_model.topics_over_time(docs=nov_jan_reviews['content'], topics=filtered_topics, timestamps=timestamps, nr_bins=nr_bins)

Length of nov_jan_reviews['content']: 13182
Length of filtered_topics: 13182
Length of timestamps: 13182

10it [02:11, 13.12s/it]

In [24]:
 # Visualize the topics over time
topic_model.visualize_topics_over_time(topics_over_time, top_n_topics=8)